# Generated by Django 4.2.26 on 2025-11-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discord_user_id', models.CharField(blank=True, db_index=True, help_text='ID do usuário no Discord', max_length=100, null=True, unique=True)),
                ('status_conversa', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('NEGOCIANDO', 'Em Negociação'), ('HANDOFF', 'Aguardando Analista')], default='NAO_INICIADO', max_length=20)),
                ('valor_total_em_negociacao', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da dívida que estava sendo negociado na ÚLTIMA interação.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Cliente Final',
                'verbose_name_plural': 'Clientes Finais',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(help_text='Código do contrato no ERP de origem', max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('cliente_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='negociacao.clientefinal')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(help_text='Nome da empresa credora', max_length=255, unique=True)),
                ('cnpj', models.CharField(help_text='CNPJ da empresa credora', max_length=14, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa Cliente',
                'verbose_name_plural': 'Empresas Clientes',
            },
        ),
        migrations.CreateModel(
            name='PoliticaNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_base_persona', models.TextField(help_text='O prompt base do sistema')),
                ('max_desconto_avista', models.DecimalField(decimal_places=2, default=25.0, help_text='Ex: 25.00 para 25%', max_digits=5)),
                ('max_parcelas', models.PositiveIntegerField(default=12, help_text='Ex: 12')),
                ('juros_parcelamento', models.DecimalField(decimal_places=2, default=1.5, help_text='Ex: 1.50 para 1.5% a.m.', max_digits=5)),
                ('empresa_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politica', to='negociacao.empresacliente')),
            ],
            options={
                'verbose_name': 'Política de Negociação',
                'verbose_name_plural': 'Políticas de Negociação',
            },
        ),
        migrations.CreateModel(
            name='HistoricoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(choices=[('USER', 'Usuário'), ('BOT', 'Bot')], max_length=10)),
                ('mensagem', models.TextField()),
                ('cliente_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='negociacao.clientefinal')),
            ],
            options={
                'verbose_name': 'Histórico de Conversa',
                'verbose_name_plural': 'Históricos de Conversa',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('NEGOCIANDO', 'Negociando'), ('PAGA', 'Paga')], db_index=True, default='PENDENTE', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='negociacao.contrato')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.AddField(
            model_name='clientefinal',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negociacao.empresacliente'),
        ),
        migrations.CreateModel(
            name='AcordoProposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_negociado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_parcelas', models.PositiveIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], db_index=True, default='PENDENTE', max_length=20)),
                ('observacoes_analista', models.TextField(blank=True, help_text='Notas do analista sobre a aprovação/rejeição')),
                ('analista_responsavel', models.ForeignKey(blank=True, help_text='Analista que aprovou/rejeitou', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='negociacao.clientefinal')),
                ('faturas_incluidas', models.ManyToManyField(related_name='acordos_propostos', to='negociacao.fatura')),
            ],
            options={
                'verbose_name': 'Acordo Proposto',
                'verbose_name_plural': 'Acordos Propostos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientefinal',
            unique_together={('empresa_cliente', 'cpf')},
        ),
    ]
