# Generated by Django 4.2.27 on 2025-12-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negociacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acordoproposto",
            name="notificado_discord",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="clientefinal",
            name="status_conversa",
            field=models.CharField(
                choices=[
                    ("NAO_INICIADO", "Não Iniciado"),
                    ("NEGOCIANDO", "Em Negociação"),
                    ("HANDOFF", "Aguardando Analista"),
                    ("CONCLUIDO", "Acordo Fechado"),
                ],
                default="NAO_INICIADO",
                max_length=20,
            ),
        ),
    ]
